node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     echo "specify docker tool"
     docker.withTool('docker') {
        withDockerServer([credentialsId: "ubdockera1", uri: "tcp://ubdockera1.mhp.lan:2376"]) { 
           docker.withRegistry('https://index.docker.io/v2/', 'docker-devmhp') {
             def app = docker.build("wardviaene/docker-nodejs-demo:${commit_id}", '.').push()
           }
        }
     }
   }
}
